[package]
name = "polkadot-node-subsystem"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Subsystem traits and message definitions and the generated overseer"

[dependencies]
polkadot-overseer = { path = "../overseer" }
polkadot-overseer-gen = { path = "../overseer/overseer-gen" }
polkadot-node-subsystem-types = { path = "../subsystem-types" }
polkadot-node-jaeger = { path = "../jaeger" }
thiserror = "1.0.23"
smallvec = "1.6.1"
futures = "0.3"
polkadot-primitives = { path = "../../primitives" }
polkadot-node-primitives = { path = "../primitives" }
polkadot-node-metrics = { path = "../metrics" }
